name: find_a_match_game_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  flutter_native_splash: ^2.3.7
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.2
  flip_card: ^0.7.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/lobby/
    - assets/images/elements/
    - assets/images/scores/
    - assets/images/game/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf

    - family: ChangaOne
      fonts:
        - asset: fonts/ChangaOne-Regular.ttf